resources:
- manager.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:b6630dd75d7b3aa785ed42e9467fc121346803a058d84a2a5703f7f07911bcec
  name: controller
  newName: image-registry.openshift-image-registry.svc:5000/hestia-operator-system/hestia
