apiVersion: e2e.stakater.com/v1alpha1
kind: Runner
metadata:
  name: runner
  labels:
    app.kubernetes.io/name: hestia-operator
    app.kubernetes.io/managed-by: kustomize
    app: runner-1
spec:
#  schedule: "* * * * *" # every minute
  deploymentSelector:
    matchLabels:
      app: test
  deadlineSeconds: 120
  template:
    spec:
      containers:
        - name: example
          image: busybox
          imagePullPolicy: IfNotPresent
          command: ["sh", "-c", "sleep 10 && echo done && exit 0"]
      restartPolicy: Never
